### ISSUE TITLE
Add certificates support for SSL connections.

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-sql#13]
The SSL connection flag doesn't make the connection safe because is not used with a certificate. The service can be vulnerable to a man-in-the-middle attack in the case of the SQL service not be deployed at the same network of the database.
Adding support for certificates validation will fix that vulnerability.

**Comment by Eric-McWhorter** [comment]
I have successfully configured IIS as a reverse proxy to handle the SSL encryption of site-to-site traffic, per recommendation of ManyWho.  Reverse proxy can be accomplished in Apache as well.

**Comment by josecollazzi** [comment]
@jonjomckay could you please review?

**Comment by josecollazzi** [comment]
@jonjomckay thank you for the comments, could you please review the changes?

**Comment by jonjomckay** [comment]
@josecollazzi LGTM :+1:
