### ISSUE TITLE
-Dserver.port property accepted but not used

### ISSUE THREAD

**Issue by Eric-McWhorter** [manywho/service-sql#14]
We need to execute Service-SQL on a port other than 8080 (default). The Service-SQL readme (https://github.com/manywho/service-sql) states that this can be accomplished by adding the following property to the executing command:

`-Dserver.port=<port>`

However, adding that command does not modify the behavior of the embedded web server. In fact, the service continues to listen only on port 8080 regardless of what port is entered for the property.

I have verified this using both netstat and a browser.

**Comment by josecollazzi** [comment]
I have added tags to the code.
@jonjomckay could you please review?

**Comment by jonjomckay** [comment]
LGTM :+1:
