### ISSUE TITLE
Searching in a list filter tries to compare against non-String fields in the generated SQL

### ISSUE THREAD

**Issue by jonjomckay** [manywho/service-sql#19]
When searching in a combobox or a table, the service generates SQL that tries to do a `LIKE` against all the columns in the type which can cause errors like `ERROR: operator does not exist: bigint ~~ unknown` in PostgreSQL.

Ideally, it should just do a `LIKE` against all the stringy columns.

**Comment by jonjomckay** [comment]
This also fixes incorrectly using an `AND` comparison instead of an `OR` when looking up the search criteria

**Comment by jonjomckay** [comment]
@josecollazzi please can you review?

**Comment by josecollazzi** [comment]
@jonjomckay LGTM

**Comment by jonjomckay** [comment]
@josecollazzi has this one been released? @chriscapp is asking about it :)
