### ISSUE TITLE
The class for the drivers are checked in each call

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-sql#20]
We should check the class for the driver only once for app (SDK 2 have support for it) 
````
Class.forName(driverConfiguration.getDriverClass());
````

**Comment by josecollazzi** [comment]
@jonjomckay could you please review?

**Comment by josecollazzi** [comment]
@jonjomckay thanks could you please review the changes?

**Comment by jonjomckay** [comment]
@josecollazzi LGTM 👍
