### ISSUE TITLE
The database connection is reused in different request

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-sql#23]
We can not reuse database connections from different requests. 
Each request should create its own connection.

**Comment by josecollazzi** [comment]
@jonjomckay could you please review?

**Comment by jonjomckay** [comment]
@josecollazzi these changes probably won't actually improve performance as you're just passing the `Sql2o` object around and opening new connections each time you use it. If you want to improve performance, you should pass the `Connection` object around that you get from `sql2o.open()` (probably by wrapping the top level in a try-resources block)

**Comment by josecollazzi** [comment]
thanks @jonjomckay  now using the connection, could you please review?
