### ISSUE TITLE
A View in order by random() in PostgreSQL is not random

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-sql#37]
The service use "order by"  by default so the SqlServer doesn't throw an exception if the user doesn't select an order by in the view. But in this scenario we have a view with order by random() in PostgreSQL and the service is ordering the rows by default. We should keep throwing the exception in SqlServer and not assume anything in the service.

SqlServer throw an exception when executing a select with a limit and order by.

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review?

**Comment by jonjomckay** [comment]
@josecollazzi LGTM :)
