### ISSUE TITLE
"problem creating objectFor input string" when saving to table with a SERIAL column in postgres

### ISSUE THREAD

**Issue by matt-manywho** [manywho/service-sql#5]
With a table like this:

CREATE TABLE public.testcase
(
    name text COLLATE "default".pg_catalog,
    id integer NOT NULL DEFAULT nextval('testcase_id_seq'::regclass),
    CONSTRAINT testcase_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)

When performing a save I get the error: "problem creating objectFor input string" however the record still gets inserted 4 times (due to ManyWho retrying).

**Comment by josecollazzi** [comment]
@matt-manywho I think this is a bug in one of the libraries that we are using, I have reported the issue https://github.com/aaberg/sql2o/issues/249 

This problem happens only in PostgreSQL when I create a table with a generated field (serial id in this case) and the generated field is also a primary key and the primary key is not in the first position of the table.

You can get a work around this problem creating the table with the id in the first position:

````
CREATE TABLE public.testcase
(
id SERIAL NOT NULL,
name text COLLATE "default".pg_catalog,
CONSTRAINT testcase_pkey PRIMARY KEY (id)
)
WITH (
OIDS = FALSE
)
````

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review? 🌵

**Comment by jonjomckay** [comment]
LGTM :dancing_women:

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review again? this fix was breaking some test
🚶

**Comment by jonjomckay** [comment]
LTGM :face_with_head_bandage:
