### ISSUE TITLE
Add the ability to define names for the generated Type properties

### ISSUE THREAD

**Issue by jonjomckay** [manywho/service-sql#9]
We should support being able to define custom names to be used for the properties on the generated Type - probably through parsing the comment field for a column.

We'd have to prefix our custom comment with something that we can detect while parsing, as to not mess up any existing comments on tables.

This will improve human-readability and allow for nicer names to be used when building flows using the SQL Service :100: 

This ticket is only for PostgreSQL

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review? 📟

**Comment by jonjomckay** [comment]
@josecollazzi seems legit :1st_place_medal:

**Comment by josecollazzi** [comment]
@jonjomckay  I have added a fix for some issues in this ticket could you please review again.

**Comment by jonjomckay** [comment]
@josecollazzi yep, all looks good :100:
